spring:
  application:
    name: shortly

  mongodb:
    uri: ${MONGO_URL}

  jackson:
    mapper:
      accept-case-insensitive-enums: true

mnotify:
  accessKey: ${MNOTIFY_API}
  sender: ShortlyPush
  baseUrl: https://api.mnotify.com/api/sms
